fragment UserParts on User {
  __typename
  users {
    __typename
    username
    name
    email
    password {
      value
      passwordChangeRequired
    }
  }
}

fragment PostParts on Post {
  __typename
  title
  date
  tags
  body
}

fragment DocParts on Doc {
  __typename
  title
  description
  tags
  body
}
